language: emacs-lisp
before_install:
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el &&
      echo `pwd` && 
      wget https://github.com/mirrors/emacs/raw/master/lisp/emacs-lisp/ert.el &&
      wget https://github.com/mirrors/emacs/raw/master/lisp/emacs-lisp/ert-x.el;
    fi
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
script:
  - emacs --version
  - emacs -batch -l ert -l test-toggle-test.el -f ert-run-tests-batch-and-exit